export default [
	{
		name: '矢量-天地图',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/tdt_vec.png',
		type: 'group',
		layers: [
			{
				name: '底图',
				type: 'tdt',
				layer: 'vec_d',
				key: $config.map_tdt_key,
			},
			{
				name: '注记',
				type: 'tdt',
				layer: 'vec_z',
				key: $config.map_tdt_key,
			},
		],
	},
	{
		name: '矢量-天地图url',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/tdt_img.png',
		type: 'group',
		layers: [
			{
				name: '底图',
				type: 'xyz',
				url: `https://t{s}.tianditu.gov.cn/vec_w/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=vec&STYLE=default&TILEMATRIXSET=w&FORMAT=tiles&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}&tk=${$config.map_tdt_key}`,
				subdomains: '01234567',
			},
			{
				name: '注记',
				type: 'xyz',
				url: `https://t{s}.tianditu.gov.cn/cva_w/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=cva&STYLE=default&TILEMATRIXSET=w&FORMAT=tiles&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}&tk=${$config.map_tdt_key}`,
				subdomains: '01234567',
			},
		],
	},
	{
		name: '矢量-高德精简',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/gaode_vec.png',
		type: 'xyz',
		url: 'https://webrd04.is.autonavi.com/appmaptile?lang=zh_cn&size=1&scale=1&style=7&x={x}&y={y}&z={z}',
		chinaCRS: 'GCJ02',
	},
	{
		name: '矢量-百度',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/bd_vec.png',
		type: 'baidu',
		layer: 'vec',
	},
	{
		name: '矢量-腾讯',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/tencent_vec.png',
		type: 'tencent',
		layer: 'vec',
		minimumLevel: 3,
		maximumLevel: 18,
	},
	{
		name: '矢量-星图',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/tdt_vec.png',
		type: 'xyz',
		url: 'https://tiles{s}.geovisearth.com/base/v1/vec/{z}/{x}/{y}?token=' + $config.map_xt_key,
		subdomains: '123',
		maximumLevel: 18,
	},
	{
		name: '矢量-谷歌',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/google_img.png',
		type: 'google',
		layer: 'vec',
	},
	{
		name: '矢量-开放街图',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/gaode_vec.png',
		type: 'xyz',
		url: `https://tile.openstreetmap.org/{z}/{x}/{y}.png`,
	},
	{
		name: '矢量-开放街图-自行车',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/gaode_vec.png',
		type: 'xyz',
		url: `https://{s}.tile-cyclosm.openstreetmap.fr/cyclosm/{z}/{x}/{y}.png`,
		subdomains: 'abc',
		divider: true,
	},
	{
		name: '矢量底图-微软',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/gaode_vec.png',
		type: 'xyz',
		url: 'https://d.basemaps.cartocdn.com/light_nolabels/{z}/{x}/{y}.png',
		divider: true,
	},
	{
		name: '卫星-天地图+高德',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/tdt_img.png',
		type: 'group',
		layers: [
			{
				name: '底图',
				type: 'tdt',
				layer: 'img_d',
				key: $config.map_tdt_key,
			},
			{
				name: '注记',
				type: 'gaode',
				layer: 'img_z',
			},
		],
		show: true,
	},
	{
		name: '卫星-高德',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/gaode_img.png',
		type: 'group',
		layers: [
			{
				name: '底图',
				type: 'gaode',
				layer: 'img_d',
			},
			{
				name: '注记',
				type: 'gaode',
				layer: 'img_z',
			},
		],
	},
	{
		name: '卫星-高德url',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/gaode_img.png',
		type: 'group',
		layers: [
			{
				name: '底图',
				type: 'xyz',
				url: 'https://webst0{s}.is.autonavi.com/appmaptile?style=6&x={x}&y={y}&z={z}',
				subdomains: '1234',
				chinaCRS: 'GCJ02',
				maximumLevel: 18,
			},
			{
				name: '注记',
				type: 'xyz',
				url: 'https://webst0{s}.is.autonavi.com/appmaptile?style=8&x={x}&y={y}&z={z}',
				subdomains: '1234',
				chinaCRS: 'GCJ02',
				maximumLevel: 18,
			},
		],
	},
	{
		name: '卫星-天地图',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/tdt_img.png',
		type: 'group',
		layers: [
			{
				name: '底图',
				type: 'tdt',
				layer: 'img_d',
				key: $config.map_tdt_key,
				contrast: 1.5, // 对比度
				gamma: 1.2, // 伽马值
			},
			{
				name: '注记',
				type: 'tdt',
				layer: 'img_z',
				key: $config.map_tdt_key,
				contrast: 1.5, // 对比度
			},
		],
	},
	{
		name: '卫星-天地图url',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/tdt_img.png',
		type: 'group',
		layers: [
			{
				name: '底图',
				type: 'xyz',
				url: `https://t{s}.tianditu.gov.cn/img_w/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=img&STYLE=default&TILEMATRIXSET=w&FORMAT=tiles&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}&tk=${$config.map_tdt_key}`,
				subdomains: '01234567',
				contrast: 1.5, // 对比度
				gamma: 1.2, // 伽马值
				maximumLevel: 18,
			},
			{
				name: '注记',
				type: 'xyz',
				url: `https://t{s}.tianditu.gov.cn/cia_w/wmts?SERVICE=WMTS&REQUEST=GetTile&VERSION=1.0.0&LAYER=cia&STYLE=default&TILEMATRIXSET=w&FORMAT=tiles&TILEMATRIX={z}&TILEROW={y}&TILECOL={x}&tk=${$config.map_tdt_key}`,
				subdomains: '01234567',
				contrast: 1.5, // 对比度
				maximumLevel: 18,
			},
		],
	},
	// {
	// 	name: '卫星-百度',
	// 	icon: 'https://data.mars3d.cn/img/thumbnail/basemap/bd_img.png',
	// 	type: 'group',
	// 	layers: [
	// 		{
	// 			name: '底图',
	// 			type: 'baidu',
	// 			layer: 'img_d',
	// 		},
	// 		{
	// 			name: '注记',
	// 			type: 'baidu',
	// 			layer: 'img_z',
	// 		},
	// 	],
	// },
	{
		name: '卫星-腾讯',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/tencent_img.png',
		type: 'group',
		layers: [
			{
				name: '底图',
				type: 'tencent',
				layer: 'img_d',
				maximumLevel: 18,
			},
			{
				name: '注记',
				type: 'tencent',
				layer: 'img_z',
				maximumLevel: 18,
			},
		],
	},
	{
		name: '卫星-星图',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/tdt_img.png',
		type: 'group',
		layers: [
			{
				name: '底图',
				type: 'xyz',
				url: 'https://tiles{s}.geovisearth.com/base/v1/img/{z}/{x}/{y}?token=' + $config.map_xt_key,
				subdomains: '123',
				maximumLevel: 18,
			},
			{
				name: '注记',
				type: 'xyz',
				url: 'https://tiles{s}.geovisearth.com/base/v1/cia/{z}/{x}/{y}?token=' + $config.map_xt_key,
				subdomains: '123',
				maximumLevel: 18,
			},
		],
	},
	{
		name: '卫星-谷歌',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/google_img.png',
		type: 'google',
		layer: 'img_d', //等同于与下一句url
		// url: 'https://gac-geo.googlecnapps.club/maps/vt?lyrs=y&x={x}&y={y}&z={z}', // lys参数可选值包括：h（街道图）、m（街道图）、p（街道图）、r（街道图）、s（影像无注记）、y（影像含注记）、t（地形图）
	},
	{
		name: '卫星底图-谷歌',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/google_img.png',
		type: 'google',
		layer: 'img_d', //等同于与下一句url
		// url: 'https://gac-geo.googlecnapps.club/maps/vt?lyrs=s&x={x}&y={y}&z={z}',
	},
	// {
	// 	name: '卫星底图-谷歌镜像',
	// 	icon: 'https://data.mars3d.cn/img/thumbnail/basemap/google_img.png',
	// 	type: 'google',
	// 	url: 'https://cbk.8ditu.com/maps/vt?lyrs=s&x={x}&y={y}&z={z}',
	// },
	{
		name: '卫星底图-ArcGIS',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/gaode_vec.png',
		type: 'xyz',
		url: 'https://server.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
	},
	{
		name: '卫星底图-吉林一号2024',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/tdt_img.png',
		type: 'xyz',
		url: 'https://api.jl1mall.com/getMap/{z}/{x}/{reverseY}?mk=3ddec00f5f435270285ffc7ad1a60ce5&tk=' + $config.map_jlyh_key,
		maximumLevel: 18,
	},
	{
		name: '卫星底图-吉林一号2023',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/tdt_img.png',
		type: 'xyz',
		url: 'https://api.jl1mall.com/getMap/{z}/{x}/{reverseY}?mk=73ad26c4aa6957eef051ecc5a15308b4&tk=' + $config.map_jlyh_key,
		maximumLevel: 18,
	},
	{
		name: '卫星底图-吉林一号2023全球',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/tdt_img.png',
		type: 'xyz',
		url: 'https://api.jl1mall.com/getMap/{z}/{x}/{reverseY}?mk=9a4ea39e1388ae1b3733faa8557b5f42&tk=' + $config.map_jlyh_key,
		maximumLevel: 18,
	},
	{
		name: '卫星底图-吉林一号2022',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/tdt_img.png',
		type: 'xyz',
		url: 'https://api.jl1mall.com/getMap/{z}/{x}/{reverseY}?mk=bd60ffe96379e0c9cbc1be02b06e3622&tk=' + $config.map_jlyh_key,
		maximumLevel: 18,
		divider: true,
	},

	// {
	// 	name: '卫星注记-谷歌',
	// 	icon: 'https://data.mars3d.cn/img/thumbnail/basemap/google_img.png',
	// 	type: 'google',
	// 	url: 'https://gac-geo.googlecnapps.club/maps/vt?lyrs=h&v=982&gl=cn&x={x}&y={y}&z={z}',
	// 	divider: true,
	// },
	{
		name: '地形-天地图',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/tdt_ter.png',
		type: 'group',
		layers: [
			{ name: '底图', type: 'tdt', layer: 'ter_d', key: $config.map_tdt_key },
			{ name: '注记', type: 'tdt', layer: 'ter_z', key: $config.map_tdt_key },
		],
	},
	{
		name: '地形-星图',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/google_ter.png',
		type: 'xyz',
		url: 'https://tiles{s}.geovisearth.com/base/v1/ter/{z}/{x}/{y}?token=' + $config.map_xt_key,
		subdomains: '123',
	},
	{
		name: '地形-谷歌',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/google_ter.png',
		type: 'google',
		layer: 'ter',
	},
	{
		name: '地形-ArcGIS',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/gaode_vec.png',
		type: 'xyz',
		url: 'https://server.arcgisonline.com/arcgis/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}',
	},
	{
		name: '地形底图-ArcGIS',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/gaode_vec.png',
		type: 'xyz',
		url: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Shaded_Relief/MapServer/tile/{z}/{y}/{x}',
	},
	// {
	// 	name: '地形底图-Smgi复古',
	// 	icon: 'https://data.mars3d.cn/img/thumbnail/basemap/gaode_vec.png',
	// 	type: 'xyz',
	// 	url: 'https://smgi.com.cn:8085/tserver/wmts.ashx?t=ter_zh_m&r={y}&c={x}&l={z}',
	// },
	// {
	// 	name: '地形底图-Smgi淡雅',
	// 	icon: 'https://data.mars3d.cn/img/thumbnail/basemap/gaode_vec.png',
	// 	type: 'xyz',
	// 	url: 'https://smgi.com.cn:8085/tserver/wmts.ashx?t=ter_dy_m&r={y}&c={x}&l={z}',
	// },
	// {
	// 	name: '地形底图-Smgi古典灰',
	// 	icon: 'https://data.mars3d.cn/img/thumbnail/basemap/gaode_vec.png',
	// 	type: 'xyz',
	// 	url: 'https://smgi.com.cn:8085/tserver/wmts.ashx?t=ter_h_m&r={y}&c={x}&l={z}',
	// },
	// {
	// 	name: '地形底图-Smgi绚丽',
	// 	icon: 'https://data.mars3d.cn/img/thumbnail/basemap/gaode_vec.png',
	// 	type: 'xyz',
	// 	url: 'https://smgi.com.cn:8085/tserver/wmts.ashx?t=ter_xl_m&r={y}&c={x}&l={z}',
	// 	divider: true,
	// },
	{
		name: '主题-静谧蓝-腾讯',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/my_blue.png',
		type: 'tencent',
		layer: 'custom',
		style: '4',
	},
	{
		name: '主题-荧光蓝-高德',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/my_blue.png',
		type: 'gaode',
		layer: 'vec',
		chinaCRS: 'GCJ02',
		invertColor: true,
		filterColor: '#4e70a6',
		brightness: 0.6,
		contrast: 1.8,
		gamma: 0.3,
		hue: 1,
		saturation: 0,
		minimumLevel: 3,
	},
	{
		name: '主题-荧光绿-高德',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/my_green.png',
		type: 'gaode',
		layer: 'vec',
		chinaCRS: 'GCJ02',
		invertColor: true,
		filterColor: 'rgba(12, 238, 230)',
		brightness: 1,
		contrast: 1.0,
		gamma: 0.2,
		hue: 1,
		saturation: 0,
		minimumLevel: 3,
	},
	{
		name: '主题-午夜黑-高德',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/my_dark.png',
		type: 'gaode',
		layer: 'vec',
		chinaCRS: 'GCJ02',
		invertColor: true,
		filterColor: '#909090',
		brightness: 0.6,
		contrast: 1.8,
		gamma: 0.3,
		hue: 1,
		saturation: 0,
		minimumLevel: 3,
		divider: true,
	},
	// {
	// 	name: '其他-本地',
	// 	icon: '/navyblue/icon.png',
	// 	type: 'xyz',
	// 	url: '/navyblue/{z}/{x}/{y}.png',
	// 	divider: true,
	// },
	{
		name: '其他-单图',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/offline.png',
		type: 'image',
		url: `${$config.cdn}/map2d/world.jpg`,
	},
	{
		name: '其他-单图夜晚',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/my_night.png',
		type: 'image',
		url: `${$config.cdn}/map2d/world_night.jpg`,
	},
	{
		name: '其他-单图深蓝',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/my_blue.png',
		type: 'image',
		url: `${$config.cdn}/map2d/world_blue.jpg`,
		divider: true,
	},
	{
		name: '其他-无底图',
		icon: 'https://data.mars3d.cn/img/thumbnail/basemap/null.png',
		type: 'grid',
		color: '#ffffff',
		alpha: 0.03,
		cells: 2,
	},
]
